## node configurations template
node:
  mode: "multiminer"
  ## the profile of node: devnet/testnet/mainnet
  profile: "testnet"
  # default chain url for miner, can be overwritten in miners[] as below
  chainWsUrl: "ws://127.0.0.1:9944/"
  # default backup chain urls for miner, can be overwritten in miners[] as below
  backupChainWsUrls: ["wss://testnet-rpc.cess.network/ws/"]

## chain configurations
## set option: '--skip-chain' or '-s' to skip installing chain (mineradm install --skip-chain)
## if set option: --skip-chain, please set official chain in miner[].chainWsUrl or others chain you know
chain:
  ## chain mode: rpcnode, the name of the rpc node
  name: "cess"
  ## the port of rpc node
  port: 30336
  ## listen at port 9944
  rpcPort: 9944

## miners configurations  (multi miners mode)
miners:
  - name: "miner1"
    # P2P communication port, each port must be different
    port: 15001
    # Maximum space used in each miner, the unit is GiB
    # The declaration space on chain is auto set by the value of `UseSpace after round up to the closest TB` when the miner first run
    # If set UseSpace 2300, that means declare 3 TiB space on the chain
    # If set UseSpace 300, that means declare 1 TiB space on the chain
    UseSpace: 1000
    # Number of cpu's processor used, 0 means use all
    UseCpu: 2
    # earnings account
    earningsAcc: "cXxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    # Staking account
    # If you fill in the staking account, the staking will be paid by the staking account,
    # otherwise the staking will be paid by the earningsAcc.
    stakingAcc: "cXxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    # Signature account mnemonic
    # each miner's mnemonic should be different
    mnemonic: "aaaaa bbbbb ccccc ddddd eeeee fffff ggggg hhhhh iiiii jjjjj kkkkk lllll"
    # miner work at this path
    diskPath: "/mnt/cess_storage1"
    # The rpc endpoint of the chain
    # `official chain: "wss://testnet-rpc.cess.network/ws/"`
    chainWsUrl: "ws://127.0.0.1:9944/"
    backupChainWsUrls: []
    # Priority tee list address
    TeeList:
      - 127.0.0.1:8080
      - 127.0.0.1:8081
    # Bootstrap Nodes
    Boot: "_dnsaddr.boot-miner-testnet.cess.network"

  - name: "miner2"
    # P2P communication port, each port must be different
    port: 15002
    # Maximum space used in each miner, the unit is GiB
    # The declaration space on chain is auto set by the value of `UseSpace after round up to the closest TB` when the miner first run
    # If set UseSpace to 2100, that means declare 3 TiB space on the chain
    # If set UseSpace to 300, that means declare 1 TiB space on the chain
    UseSpace: 1000
    # Number of cpu's processor used
    UseCpu: 2
    # earnings account
    earningsAcc: "cXxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    # Staking account
    # If you fill in the staking account, the staking will be paid by the staking account,
    # otherwise the staking will be paid by the earningsAcc.
    stakingAcc: "cXxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    # Signature account mnemonic
    # each miner's mnemonic should be different
    mnemonic: "lllll kkkkk jjjjj iiiii hhhhh ggggg fffff eeeee ddddd ccccc bbbbb aaaaa"
    # miner work at this path
    diskPath: "/mnt/cess_storage2"
    # The rpc endpoint of the chain
    # `official chain: "wss://testnet-rpc.cess.network/ws/"`
    chainWsUrl: "ws://127.0.0.1:9944/"
    backupChainWsUrls: []
    # Priority tee list address
    TeeList:
      - 127.0.0.1:8080
      - 127.0.0.1:8081
    # Bootstrap Nodes
    Boot: "_dnsaddr.boot-miner-testnet.cess.network"

# miners monitor service, send alert with email/webhook when miners is down or get punishment
watchdog:
  # enable miners monitor or not
  enable: false
  # external: server run with 0.0.0.0 or 127.0.0.1
  external: true
  # apiUrl: watchdog-web request this apiUrl to fetch data from watchdog: <my_public_ip:13081 or a domain>
  apiUrl: ""
  # watchdog server listen http port at: 13081
  port: 13081
  # the interval of query data from chain for each miner, 30 <= scrapeInterval <= 300
  scrapeInterval: 60
  # watchdog can scrape miners data from this hosts
  hosts:
    - ip: 127.0.0.1 # 127.x, 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16 is a private IP
      # make sure docker daemon listen at 2375: https://docs.docker.com/config/daemon/remote-access/
      port: 2375
    # Configure remote access for Docker daemon in public network must use tls to make sure mnemonic safe
    # set ca/crt/key path if the ip no belongs to [ 127.x, 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16 ]
    - ip: 1.1.1.1 # 1.1.1.1 is a public IP
      # make sure docker daemon tls listen at 2376: https://docs.docker.com/engine/security/protect-access/
      port: 2376
      # please make sure each file name is unique
      ca_path: /etc/docker/tls/1.1.1.1-ca.pem
      cert_path: /etc/docker/tls/1.1.1.1-cert.pem
      key_path: /etc/docker/tls/1.1.1.1-key.pem
  alert:
    # enable alert or not
    enable: false
    # send webhook to alert someone
    webhook:
      - https://hooks.slack.com/services/XXXXXXXXX/XXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXX
      - https://discordapp.com/api/webhooks/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    # send email to alert someone
    email:
      smtp_endpoint: smtp.example.com
      smtp_port: 80
      smtp_account: myservice@example.com
      smtp_password: my_pwd
      receiver:
        - example1@gmail.com
        - example2@outlook.com